modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "kubejsoffline"
version = "${version}"
displayName = "KubeJS Offline (Forge)"
authors = "ILIKEPIEFOO2"
description = '''
A mod that makes KubeJS documentation available offline.
'''
#logoFile = ""

[[dependencies.kubejsoffline]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsoffline]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsoffline]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.63,)"
ordering = "AFTER"
side = "BOTH"