# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
enabled_platforms=neoforge
archives_base_name=kubejsoffline
# Mod Properties
mod_id=kubejsoffline
mod_name=KubeJS Offline
mod_version=5.0.4
mod_description=This mod is designed to be used with KubeJS to allow for dynamic documentation that is usable offline. Run /kubejs_offline to generate the documentation.
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/kubejs-offline
mod_source=https://github.com/Hunter19823/kubejsoffline
mod_author=ILIKEPIEFOO2
mod_logo=kubejs_offline_logo.png
license=All Rights Reserved
maven_group=pie.ilikepiefoo
curseforge_id=641627
modrinth_id=7I1fu1km
artifact_type=release
common_mixin=kubejsoffline-common.mixins.json
neoforge_mixin=kubejsoffline.mixins.json
neoforge_config=META-INF/neoforge.mods.toml
minecraft_version=1.21
neoforge_version=21.0.148
fabric_loader_version=N/A
fabric_api_version=N/A
kubejs_version=2101.7.1-build.181
architectury_version=13.0.8
reflections_version=0.10.2
javassist_version=3.28.0-GA
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.7-SNAPSHOT
unified_publishing_version=0.1.+
shadowjar_version=8.1.1
github_commit_hash=unknown
core_version=1.0.4