org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=false

group=pie.ilikepiefoo
modId=kubejsoffline
modName=KubeJS Offline
modVersion=5.2.1
minecraftVersion=1.21
modDescription=This mod is designed to be used with KubeJS to allow for dynamic documentation that is usable offline. Run /kubejs_offline to generate the documentation.
modAuthor=ILIKEPIEFOO2
modLicense=All Rights Reserved
modHomepage=https://www.curseforge.com/minecraft/mc-mods/kubejs-offline
modSource=https://github.com/Hunter19823/kubejsoffline
modIssues=https://github.com/Hunter19823/kubejsoffline/issues
modIcon=assets/kubejsoffline/kubejs_offline_logo.png

neoforgeVersion=21.0.148
neoforgeVersions=[21.0.148,)
kubejsVersion=2101.7.1-build.181
architecturyVersion=13.0.8
coreVersion=1.2.0.37
reflectionsVersion=0.10.2

supportedVersions=1.21, 1.21.1
curseforgeId=641627
modrinthId=7I1fu1km
uploadType=release

githubCommitHash=unknown
