name: Publish the minecraft mod to CurseForge and Modrinth

on:
  push:
    branches:
      - "1.20.1"

permissions:
  contents: read
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    if: contains(github.event.head_commit.message, '[RELEASE]') || contains(github.event.head_commit.message, '[DOCUMENTATION]')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Initialize caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
            ~/.minecraft/assets
          key: ${{ runner.os }}-${{ github.ref }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-build-

      - name: Make the gradle wrapper executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}

      - name: Publish Unified
        if: contains(github.event.head_commit.message, '[RELEASE]')
        run: ./gradlew publishUnified
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Generate Documentation (Fabric)
        if: contains(github.event.head_commit.message, '[DOCUMENTATION]')
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew :fabric:runClient
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}
          KUBEJS_OFFLINE_AUTO_GEN: 'true'

      - name: Generate Documentation (Forge)
        if: contains(github.event.head_commit.message, '[DOCUMENTATION]')
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew :forge:runClient
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}
          KUBEJS_OFFLINE_AUTO_GEN: 'true'

      - name: Update Documentation
        if: contains(github.event.head_commit.message, '[DOCUMENTATION]')
        run: ./gradlew updateDocumentation
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}

      - name: Commit Documentation
        if: contains(github.event.head_commit.message, '[DOCUMENTATION]')
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'Updated documentation for build ${{ github.run_number }}'
          file_pattern: '*.html'


