name: Publish the minecraft mod to CurseForge and Modrinth

on:
  push:
    branches:
      - "1.20.1"

permissions:
  contents: read
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make the gradle wrapper executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}

      - name: Publish Unified
        run: ./gradlew publishUnified
        env:
          BUILD_VERSION: ${{ github.run_number }}
          PACKAGE_ACTOR: ${{ secrets.PACKAGE_ACTOR }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_PAT }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
